#faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as possíveis informações possíveis sobre ele.
exemplo =input('digite algo:')
print('o tipo primitivo desse valor é', type(exemplo))
print(exemplo.isnumeric())
print(exemplo.isalpha())
print(exemplo.islower())
print(exemplo.isupper())
print(exemplo.istitle())
#correção
exemplo =input('digite algo:')
print('o tipo primitivo desse valor é', type(exemplo))
print('é numérico?', exemplo.isnumeric())
print('contém apenas letras?', exemplo.isalpha())
print('todas as letras são minúsculas?', exemplo.islower())
print('todas as letras são maiúsculas?', exemplo.isupper())
print('a primeira letra é maiúscula?', exemplo.istitle())
